name: docs ⚙️

on:
  push:
    branches:
    - master
    paths:
    - 'docs/**'

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install requirements 📦
        run: |
          pip3 install mkdocs
      - name: Deploy 📦
        run: cd docs && mkdocs gh-deploy --force -m 'update website'
