name: build ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v6
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies 📦
      run: sudo apt-get update && sudo apt-get install -y dh-python devscripts debhelper pybuild-plugin-pyproject build-essential python3-all
    - name: Install package and doc requirements 📦
      run: |
        pip3 install .
        pip3 install ".[dev]"
        pip3 install ".[docs]"
        pip3 install ".[release]"
    - name: build docs 🏗️
      run: mkdocs build -f docs/mkdocs.yml
    - name: run flake8 ⚙️
      run: flake8
    - name: build Python package 🏗️
      run: python3 -m build
    - name: build Debian package 🏗️
      run: sudo debuild -b -uc -us
